version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: trash-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: trash-frontend
    ports:
      - "3000:80"
    restart: always
